services:
  # PostgreSQL database for Prefect server
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prefect-network

  # Prefect server
  prefect-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "4200:4200"
    environment:
      PREFECT_API_URL: http://localhost:4200/api
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_SERVER_API_PORT: 4200
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
      PREFECT_SERVER_DATABASE_TIMEOUT: 10
      PREFECT_API_SERVICES_SCHEDULER_ENABLED: true
      PREFECT_SERVER_ANALYTICS_ENABLED: false
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4200/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - prefect_data:/opt/prefect
      - ./deploy.py:/opt/prefect/deploy.py
    networks:
      - prefect-network

  # Prefect worker
  prefect-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    depends_on:
      prefect-server:
        condition: service_healthy
    networks:
      - prefect-network
    volumes:
      - ./flows:/opt/prefect/flows
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  

networks:
  prefect-network:
    driver: bridge

volumes:
  postgres_data:
  prefect_data: