version: '3.8'

services:
  # PostgreSQL database for Prefect server
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Prefect server
  prefect-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "4200:4200"
    environment:
      PREFECT_API_URL: http://localhost:4200/api
      PREFECT_SERVER_API_HOST: 0.0.0.0
      PREFECT_SERVER_API_PORT: 4200
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:prefect@postgres:5432/prefect
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - prefect_data:/opt/prefect
    command: prefect server start --host 0.0.0.0

  # Prefect worker
  prefect-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    depends_on:
      - prefect-server
    volumes:
      - ./flows:/opt/prefect/flows
      - /var/run/docker.sock:/var/run/docker.sock
    command: prefect worker start --pool default-pool --type process

  # Optional: Agent for running flows
  prefect-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    depends_on:
      - prefect-server
    volumes:
      - ./flows:/opt/prefect/flows
    command: prefect agent start -q default

volumes:
  postgres_data:
  prefect_data: